#!/usr/bin/env bash
# ============================================================
#  AppWay Feedback Site – Deploy script
#  Uses the EC2 instance role (no --profile needed).
#
#  Usage:  ./deploy.sh
# ============================================================
set -euo pipefail

REGION="eu-west-1"
STACK="appway-feedback"
ACCOUNT="911167932273"
DEPLOY_BUCKET="appway-feedback-deploy-${ACCOUNT}-${REGION}"

# ── Email configuration ──────────────────────────────────────
TO_ADDRESSES="darkfenner69@gmail.com,dottpaolomilani@hotmail.com"
FROM_ADDRESS="darkfenner69@gmail.com"

# ── Resolve paths ────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAMBDA_DIR="${SCRIPT_DIR}/lambda"
PUBLIC_DIR="${SCRIPT_DIR}/public"
INFRA_DIR="${SCRIPT_DIR}/infra"
LAMBDA_ZIP="${SCRIPT_DIR}/lambda.zip"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  AppWay Feedback – Deploy"
echo "  Region  : ${REGION}"
echo "  Stack   : ${STACK}"
echo "  Account : ${ACCOUNT}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Step 1: Ensure deploy bucket exists ─────────────────────
echo ""
echo "[1/6] Ensuring deploy bucket: ${DEPLOY_BUCKET}"
if aws s3api head-bucket --bucket "${DEPLOY_BUCKET}" --region "${REGION}" 2>/dev/null; then
  echo "      ✓ bucket exists"
else
  echo "      Creating bucket..."
  aws s3api create-bucket \
    --bucket "${DEPLOY_BUCKET}" \
    --region "${REGION}" \
    --create-bucket-configuration LocationConstraint="${REGION}"
  aws s3api put-public-access-block \
    --bucket "${DEPLOY_BUCKET}" \
    --public-access-block-configuration \
      BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
  echo "      ✓ bucket created"
fi

# ── Step 2: Zip Lambda ───────────────────────────────────────
echo ""
echo "[2/6] Packaging Lambda..."
rm -f "${LAMBDA_ZIP}"
( cd "${LAMBDA_DIR}" && zip -q "${LAMBDA_ZIP}" submit_feedback.py )
echo "      ✓ ${LAMBDA_ZIP}"

# ── Step 3: Upload Lambda zip to deploy bucket ───────────────
echo ""
echo "[3/6] Uploading Lambda package to S3..."
aws s3 cp "${LAMBDA_ZIP}" "s3://${DEPLOY_BUCKET}/lambda.zip" --region "${REGION}"
echo "      ✓ s3://${DEPLOY_BUCKET}/lambda.zip"

# ── Step 4: Deploy CloudFormation stack ─────────────────────
echo ""
echo "[4/6] Deploying CloudFormation stack '${STACK}'..."
aws cloudformation deploy \
  --template-file "${INFRA_DIR}/template.yaml" \
  --stack-name "${STACK}" \
  --region "${REGION}" \
  --capabilities CAPABILITY_NAMED_IAM \
  --parameter-overrides \
      DeployBucket="${DEPLOY_BUCKET}" \
      LambdaKey="lambda.zip" \
      ToAddresses="${TO_ADDRESSES}" \
      FromAddress="${FROM_ADDRESS}" \
  --no-fail-on-empty-changeset
echo "      ✓ stack deployed"

# ── Step 5: Retrieve stack outputs ──────────────────────────
echo ""
echo "[5/6] Retrieving stack outputs..."

SITE_BUCKET=$(aws cloudformation describe-stacks \
  --stack-name "${STACK}" \
  --region "${REGION}" \
  --query 'Stacks[0].Outputs[?OutputKey==`SiteBucket`].OutputValue' \
  --output text)

DIST_ID=$(aws cloudformation describe-stacks \
  --stack-name "${STACK}" \
  --region "${REGION}" \
  --query 'Stacks[0].Outputs[?OutputKey==`DistributionId`].OutputValue' \
  --output text)

SITE_URL=$(aws cloudformation describe-stacks \
  --stack-name "${STACK}" \
  --region "${REGION}" \
  --query 'Stacks[0].Outputs[?OutputKey==`SiteURL`].OutputValue' \
  --output text)

API_URL=$(aws cloudformation describe-stacks \
  --stack-name "${STACK}" \
  --region "${REGION}" \
  --query 'Stacks[0].Outputs[?OutputKey==`ApiURL`].OutputValue' \
  --output text)

echo "      Site bucket : ${SITE_BUCKET}"
echo "      CF dist id  : ${DIST_ID}"
echo "      Site URL    : ${SITE_URL}"
echo "      API URL     : ${API_URL}"

# ── Inject API URL into a config.js that index.html loads ───
# We create public/config.js on-the-fly (not committed to git)
CONFIG_JS="${PUBLIC_DIR}/config.js"
cat > "${CONFIG_JS}" <<EOF
/* Auto-generated by deploy.sh – do not commit */
window.FEEDBACK_API_URL = "${API_URL}";
EOF

# Inject config.js into index.html if not already present
if ! grep -q 'config.js' "${PUBLIC_DIR}/index.html"; then
  sed -i 's|<script src="app.js"></script>|<script src="config.js"></script>\n    <script src="app.js"></script>|' \
    "${PUBLIC_DIR}/index.html"
fi

# ── Step 6: Sync public/ to S3 and invalidate CloudFront ────
echo ""
echo "[6/6] Syncing site files to S3..."
aws s3 sync "${PUBLIC_DIR}/" "s3://${SITE_BUCKET}/" \
  --delete \
  --region "${REGION}" \
  --cache-control "max-age=300"

# Set longer cache for immutable assets
for ext in css js png jpg svg ico; do
  aws s3 cp "s3://${SITE_BUCKET}/" "s3://${SITE_BUCKET}/" \
    --recursive \
    --exclude "*" \
    --include "*.${ext}" \
    --metadata-directive REPLACE \
    --cache-control "max-age=86400" \
    --region "${REGION}" \
    2>/dev/null || true
done

echo "      ✓ files synced"

echo ""
echo "      Invalidating CloudFront cache..."
aws cloudfront create-invalidation \
  --distribution-id "${DIST_ID}" \
  --paths "/*" \
  --region "${REGION}" \
  --query 'Invalidation.Id' --output text | xargs -I{} echo "      Invalidation: {}"

# ── Done ─────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅  DEPLOYMENT COMPLETE"
echo ""
echo "  Site URL (for Heyex hyperlink):"
echo ""
echo "    ${SITE_URL}"
echo ""
echo "  CloudFront distributions take ~5-10 min to propagate"
echo "  globally on first deploy. Subsequent deploys are instant."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
