"""
Generates an AppWay-compliant DICOM Encapsulated PDF (ePDF) result report.

Spec references:
  - SOPClass: 1.2.840.10008.5.1.4.1.1.104.1 (Encapsulated PDF Storage)
  - Service Manual: Heidelberg AppWay Interface Description V4
  - Credential block (0011,10xx) must be copied from input DICOM unchanged

PDF body is generated by ``appway_backend.pdf_report`` (pixel-faithful
template-overlay implementation). This module is responsible ONLY for
the DICOM wrapper and for translating the inference result dicts into
the ``ReportJob`` dataclass that the PDF generator expects.
"""
import logging
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import pydicom
from pydicom.dataset import Dataset, FileMetaDataset
from pydicom.sequence import Sequence
from pydicom.uid import generate_uid, ExplicitVRLittleEndian

from . import config
from .pdf_report import build_pdf, ReportJob, InputFileInfo, PerImageResult

logger = logging.getLogger(__name__)

SOLUTION_NAME = "MyopicCNV+"


def _resolve_solution_version() -> str:
    """
    Read the solution version from the project's ``pyproject.toml`` (which is
    always shipped next to the source). This is what gets written into the
    DICOM ``SoftwareVersions`` tag (0018,1020) and into the visible
    "Software: MyopicCNV+ v…" line on page 1 of the PDF.

    Resolution order:
      1. Installed package metadata via ``importlib.metadata`` — works when
         the project is actually installed (``pip install .`` / a wheel).
      2. Raw parse of ``pyproject.toml`` two directories up from this file —
         this is the real path at runtime on the backend EC2, because uv
         runs the project in editable/non-packaged mode and there is no
         installed distribution to query.
      3. Fallback ``"0.0.0-unknown"`` so PDF generation never crashes on
         version-string retrieval.
    """
    # 1) installed-metadata path
    try:
        from importlib.metadata import version as _pkg_version, PackageNotFoundError
        try:
            return _pkg_version("appway-backend")
        except PackageNotFoundError:
            pass
    except Exception:
        pass

    # 2) raw pyproject.toml parse (covers the uv non-packaged case)
    try:
        import tomllib  # Python 3.11+ stdlib
        pyproject = Path(__file__).resolve().parent.parent / "pyproject.toml"
        if pyproject.is_file():
            with pyproject.open("rb") as f:
                data = tomllib.load(f)
            v = (data.get("project") or {}).get("version")
            if isinstance(v, str) and v:
                return v
    except Exception:
        pass

    # 3) ultimate fallback
    return "0.0.0-unknown"


SOLUTION_VERSION = _resolve_solution_version()
ENCAPSULATED_PDF_SOPCLASS = "1.2.840.10008.5.1.4.1.1.104.1"


# ─────────────────────────────────────────────────────────────────────────
# Helpers shared between generate_epdf_dcm and generate_error_epdf_dcm
# ─────────────────────────────────────────────────────────────────────────

def _collect_input_info(dcm_files: list[Path]) -> tuple[list[dict], Optional[Dataset]]:
    """
    Read all input DICOM files.
    Returns:
      - list of per-file metadata dicts for the PDF
      - first successfully read Dataset (used as donor for patient/study tags
        + credential block)
    """
    infos = []
    donor_ds = None

    for dcm_path in sorted(dcm_files):
        try:
            ds = pydicom.dcmread(str(dcm_path), stop_before_pixels=True)
            if donor_ds is None:
                donor_ds = ds
            arr_shape = None
            try:
                rows = int(getattr(ds, "Rows", 0))
                cols = int(getattr(ds, "Columns", 0))
                nframes_tag = getattr(ds, "NumberOfFrames", None)
                nframes = int(nframes_tag) if nframes_tag else 1
                arr_shape = (nframes, rows, cols)
            except Exception:
                pass

            infos.append({
                "filename": dcm_path.name,
                "modality": getattr(ds, "Modality", ""),
                "study_description": getattr(ds, "StudyDescription", ""),
                "series_description": getattr(ds, "SeriesDescription", ""),
                "frames": arr_shape[0] if arr_shape else 1,
                "rows": arr_shape[1] if arr_shape else 0,
                "columns": arr_shape[2] if arr_shape else 0,
                "sop_instance_uid": str(getattr(ds, "SOPInstanceUID", "")),
                "sop_class_uid": str(getattr(ds, "SOPClassUID", "")),
                "series_instance_uid": str(getattr(ds, "SeriesInstanceUID", "")),
                "study_instance_uid": str(getattr(ds, "StudyInstanceUID", "")),
            })
        except Exception as e:
            logger.warning("Could not read DICOM %s: %s", dcm_path.name, e)
            infos.append({"filename": dcm_path.name})

    return infos, donor_ds


def _find_png(filename: str, png_dirs: Optional[list[Path]]) -> Optional[Path]:
    """
    Resolve a per-image PNG filename to an absolute path by searching
    ``png_dirs`` in order. Returns the first hit, or None if not found /
    if ``png_dirs`` is None.
    """
    if not png_dirs:
        return None
    for d in png_dirs:
        try:
            cand = Path(d) / filename
            if cand.is_file():
                return cand
        except Exception:
            continue
    # Slow-path fallback: search recursively.
    for d in png_dirs:
        try:
            for p in Path(d).rglob(filename):
                if p.is_file():
                    return p
        except Exception:
            continue
    return None


def _build_pdf_bytes(
    job_id: str,
    input_dcm_infos: list[dict],
    processed_at: datetime,
    inference_result: Optional[dict] = None,
    png_dirs: Optional[list[Path]] = None,
) -> bytes:
    """
    Build the PDF body using the pixel-faithful template-overlay generator
    and return it as raw bytes.

    Translates the legacy dict-based interface (used by the rest of this
    module) into the ``ReportJob`` dataclass expected by ``build_pdf``.

    ``inference_result`` shape (from inference.run_inference):
        verdict:         "positive" | "negative"
        processing_time: float
        per_image:       list of {filename, pred, conf, bbox}

    Full PNG filenames are preserved as-is in ``PerImageResult.filename``
    (no display-name shortening). ``image_path`` is resolved via
    ``_find_png`` so positives can show the annotated OCT image in the
    gallery pages.
    """
    # ── Build InputFileInfo list ──
    inputs = [
        InputFileInfo(
            filename=i.get("filename", "unknown.dcm"),
            modality=i.get("modality", ""),
            study_description=i.get("study_description", ""),
            series_description=i.get("series_description", ""),
            frames=i.get("frames") or 1,
            rows=i.get("rows") or 0,
            columns=i.get("columns") or 0,
        )
        for i in input_dcm_infos
    ]

    # ── Build PerImageResult list ──
    per_image: list[PerImageResult] = []
    verdict = "Negative"
    processing_time = 0.0

    if inference_result is not None:
        verdict = (inference_result.get("verdict") or "Negative").strip().capitalize()
        processing_time = float(inference_result.get("processing_time") or 0.0)
        for item in inference_result.get("per_image") or []:
            fname = item.get("filename") or "unknown.png"
            pred = int(item.get("pred") or 0)
            conf_raw = item.get("conf")
            conf = float(conf_raw) if conf_raw is not None else None
            bbox_raw = item.get("bbox") or []
            bbox = list(bbox_raw) if bbox_raw else []
            # Resolve full on-disk path for positive images so the
            # gallery page can stamp the annotated OCT frame.
            image_path = _find_png(fname, png_dirs) if pred == 1 else None
            per_image.append(PerImageResult(
                filename=fname,          # full filename, no shortening
                pred=pred,
                conf=conf,
                bbox=bbox,
                image_path=image_path,
            ))

    job = ReportJob(
        job_id=job_id,
        processed_at=processed_at,
        software_version=SOLUTION_VERSION,
        input_files=inputs,
        verdict=verdict,
        processing_time=processing_time,
        per_image=per_image,
    )

    # Write to a temp file (build_pdf needs a Path, not an in-memory buffer)
    # then read back as bytes and clean up.
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
        tmp_path = Path(f.name)
    try:
        build_pdf(job, tmp_path)
        return tmp_path.read_bytes()
    finally:
        try:
            tmp_path.unlink(missing_ok=True)
        except Exception:
            pass


def _build_error_pdf_bytes(
    job_id: str,
    error_message: str,
    processed_at: datetime,
) -> bytes:
    """
    Build a minimal "processing error" PDF using the pixel-faithful
    generator. We reuse the normal ``build_pdf`` path with a synthetic
    ``ReportJob`` that carries the error text in ``app_description``
    and has zero per_image rows — so the output is: summary page (error
    card) + table page (empty).

    Per spec §9.2: "Processing errors … shall be forwarded to the
    customer for information within the key measurement object (AI
    Result) as written text in the PDF part of the Key Measurement
    Report."
    """
    # Safe-escape the error message (no HTML needed for our generator,
    # but strip any stray newlines that would break the single-line text
    # fields on the summary page).
    safe_err = (error_message or "Unknown error")[:500]

    # We piggyback the error text onto ``app_description`` so the
    # generator renders it in the APP DESCRIPTION band on the summary
    # page. The verdict card will show "INACTIVE" (negative), which is
    # visually distinct from a real result and signals to the clinician
    # that this is a processing-failure notice.
    error_body = (
        f"PROCESSING ERROR — this report could not be completed.\n\n"
        f"Job: {job_id}\n"
        f"Processed: {processed_at.strftime('%Y-%m-%d %H:%M:%S UTC')}\n"
        f"Software: {SOLUTION_NAME} v{config.CLINICAL_TRIAL_PROTOCOL_VERSION}\n\n"
        f"Error:\n{safe_err}\n\n"
        "No clinical conclusion can be drawn from this report. "
        "Please contact the solution provider if the problem persists."
    )

    job = ReportJob(
        job_id=job_id,
        processed_at=processed_at,
        software_version=SOLUTION_VERSION,
        input_files=[
            InputFileInfo(
                filename="(error — input not processed)",
                modality="",
                study_description="",
                series_description="",
                frames=0,
            )
        ],
        verdict="Negative",   # renders blue "INACTIVE" card as a neutral placeholder
        processing_time=0.0,
        per_image=[],
        app_description=error_body,
    )

    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
        tmp_path = Path(f.name)
    try:
        build_pdf(job, tmp_path)
        return tmp_path.read_bytes()
    finally:
        try:
            tmp_path.unlink(missing_ok=True)
        except Exception:
            pass


# ─────────────────────────────────────────────────────────────────────────
# DICOM wrapper helpers (shared between success and error paths)
# ─────────────────────────────────────────────────────────────────────────

# Heidelberg's own ePDF generator uses these file-meta values.
# We mirror them so HEYEX doesn't reject our file on meta validation.
HD_IMPLEMENTATION_CLASS_UID  = "1.2.276.0.30.3"
HD_IMPLEMENTATION_VERSION    = "3.00"    # SH max 16 chars ✓


def _base_dicom_dataset(
    donor_ds: Optional[Dataset],
    date_str: str,
    time_str: str,
) -> Dataset:
    """
    Construct a Dataset with file meta, copy patient/study tags from
    ``donor_ds``.

    Modelled on the Heidelberg gold-standard ePDF (docs/examples/
    Example HD AppWay Result Report DICOM ePDF.dcm):
      - ImplementationClassUID / ImplementationVersionName in file meta
      - NO ClinicalTrial tags (gold has none)
      - NO Manufacturer / SoftwareVersions tags (gold has none)
      - NO ReferencedStudy/Series/InstanceSequence (gold has none)
      - StudyDescription deduplicated (strip leading "External Patient: " prefix)

    The caller still needs to fill: SeriesDescription, DocumentTitle,
    EncapsulatedDocument, ConceptNameCodeSequence, etc.
    """
    ds = Dataset()

    # ── File meta — mirror Heidelberg's implementation identifiers ────────
    file_meta = FileMetaDataset()
    file_meta.MediaStorageSOPClassUID    = ENCAPSULATED_PDF_SOPCLASS
    file_meta.MediaStorageSOPInstanceUID = generate_uid()
    file_meta.TransferSyntaxUID          = ExplicitVRLittleEndian
    file_meta.ImplementationClassUID     = HD_IMPLEMENTATION_CLASS_UID
    file_meta.ImplementationVersionName  = HD_IMPLEMENTATION_VERSION
    ds.file_meta = file_meta
    ds.preamble = b"\x00" * 128

    # ── Copy patient / study tags from donor ──────────────────────────────
    if donor_ds is not None:
        for kw in ["PatientName", "PatientID", "PatientBirthDate", "PatientSex",
                   "StudyInstanceUID", "StudyDate", "StudyTime", "StudyID",
                   "StudyDescription", "AccessionNumber", "ReferringPhysicianName",
                   "AdmissionID"]:
            if hasattr(donor_ds, kw):
                setattr(ds, kw, getattr(donor_ds, kw))

    # ── De-duplicate StudyDescription ────────────────────────────────────
    # HEYEX sometimes prefixes "External Patient: " when building the
    # test DICOM, which can propagate as a double-prefix on re-use.
    # Normalise to at most one occurrence.
    if hasattr(ds, "StudyDescription"):
        sd = str(ds.StudyDescription or "")
        prefix = "External Patient: "
        while sd.startswith(prefix + prefix):
            sd = sd[len(prefix):]
        ds.StudyDescription = sd

    # ── SOP Common ────────────────────────────────────────────────────────
    ds.SOPClassUID      = ENCAPSULATED_PDF_SOPCLASS
    ds.SOPInstanceUID   = file_meta.MediaStorageSOPInstanceUID
    ds.SpecificCharacterSet = "ISO_IR 192"

    # ── General Series ────────────────────────────────────────────────────
    ds.Modality           = "DOC"
    ds.SeriesInstanceUID  = generate_uid()
    ds.SeriesNumber       = "1000"
    ds.SeriesDate         = date_str
    ds.SeriesTime         = time_str
    ds.ConversionType     = "WSD"

    # ── General Image / Document ──────────────────────────────────────────
    ds.InstanceNumber     = "1"
    ds.ContentDate        = date_str
    ds.ContentTime        = time_str
    ds.AcquisitionDate    = date_str
    ds.AcquisitionTime    = time_str
    ds.AcquisitionDateTime = date_str + time_str
    ds.BurnedInAnnotation = "YES"
    ds.FrameOfReferenceUID = generate_uid()
    ds.StudyID = getattr(donor_ds, "StudyID", "no id") if donor_ds else "no id"

    return ds


def _attach_referenced_inputs(
    ds: Dataset,
    input_infos: list[dict],
) -> None:
    """
    NOTE (gold-standard comparison 2026-05-17):
    The Heidelberg gold-standard ePDF does NOT include
    ReferencedStudySequence, ReferencedSeriesSequence, or
    ReferencedInstanceSequence. Adding them caused HEYEX to hang
    indefinitely on "result pending". This function is intentionally
    a no-op — kept as a named function for future reference.

    HEYEX routes the result back via the credential block (0x0011),
    NOT via DICOM reference sequences.
    """
    # Do NOT populate any reference sequences — gold standard has none.
    pass


def _copy_credential_block(ds: Dataset, donor_ds: Optional[Dataset], job_id: str) -> None:
    """
    Copy the AppWay credential block (group 0x0011) from ``donor_ds``.

    ⚠️  DEVELOPER RULE (B11 in docs/next-steps.md, spec §9.2):
    The AppWay credential block (group 0x0011, "0011,10xx") is the ONLY
    private DICOM tag group that may appear on a result.dcm. Do NOT add
    any other private tags — not here, not in the error-path ePDF, not
    anywhere else in the result DICOM construction.
    """
    if donor_ds is None:
        return
    try:
        for elem in donor_ds:
            if elem.tag.group == 0x0011:
                ds.add(elem)
        logger.info("[%s] Credential block copied from donor DICOM", job_id)
    except Exception as e:
        logger.warning("[%s] Could not copy credential block: %s", job_id, e)


# ─────────────────────────────────────────────────────────────────────────
# Public entry points
# ─────────────────────────────────────────────────────────────────────────

def generate_epdf_dcm(
    job_id: str,
    input_dir: Path,
    output_path: Path,
    inference_result: Optional[dict] = None,
    png_dirs: Optional[list[Path]] = None,
) -> None:
    """
    Generate a DICOM Encapsulated PDF result report for MyopicCNV+.

    - Reads all .dcm files in input_dir for metadata
    - Builds an A4 PDF report via the pixel-faithful template-overlay
      generator (``appway_backend.pdf_report.build_pdf``)
    - Wraps it in a DICOM ePDF object
    - Copies the AppWay credential block from the first input DICOM
    - Saves to output_path

    Args:
        job_id:           unique job identifier
        input_dir:        directory with the original .dcm files
        output_path:      destination for the result.dcm
        inference_result: optional dict returned by inference.run_inference()
                          with keys verdict, processing_time, per_image.
        png_dirs:         optional list of directories (one per input DICOM)
                          where the processor dumped the extracted PNG frames.
                          Used by the gallery renderer to load positive images
                          and stamp a red bounding box + confidence chip.
    """
    dcm_files = sorted(input_dir.rglob("*.dcm"))
    if not dcm_files:
        raise ValueError(f"No .dcm files found in {input_dir}")

    now = datetime.now(timezone.utc)
    date_str = now.strftime("%Y%m%d")
    time_str = now.strftime("%H%M%S")

    # ── Collect metadata ──
    input_infos, donor_ds = _collect_input_info(dcm_files)

    # ── Build PDF ──
    pdf_bytes = _build_pdf_bytes(
        job_id, input_infos, now,
        inference_result=inference_result,
        png_dirs=png_dirs,
    )
    logger.info("[%s] Generated PDF: %d bytes", job_id, len(pdf_bytes))

    # ── Build DICOM dataset ──
    # DocumentTitle and SeriesDescription are VR LO (max 64 chars).
    # "MyopicCNV+ Result for Job <uuid>" = 68 chars → truncate label to fit.
    short_title = f"{SOLUTION_NAME} Result {job_id}"[:64]
    ds = _base_dicom_dataset(donor_ds, date_str, time_str)
    ds.SeriesDescription = short_title
    ds.ImageComments = f"Result from {SOLUTION_NAME}"
    ds.DocumentTitle = short_title
    ds.MIMETypeOfEncapsulatedDocument = "application/pdf"
    ds.EncapsulatedDocument = pdf_bytes
    ds.ConceptNameCodeSequence = Sequence([])

    _attach_referenced_inputs(ds, input_infos)

    # ── Copy AppWay credential block (0011,10xx) — mandatory for routing ──
    # ⚠️  See _copy_credential_block doc-comment for the strict no-other-
    # private-tags rule.
    _copy_credential_block(ds, donor_ds, job_id)

    # ── Save ──
    output_path.parent.mkdir(parents=True, exist_ok=True)
    ds.save_as(str(output_path), implicit_vr=False, little_endian=True)
    logger.info("[%s] ePDF DICOM saved → %s  (%d bytes)", job_id, output_path, output_path.stat().st_size)


def generate_error_epdf_dcm(
    job_id: str,
    input_dir: Path,
    output_path: Path,
    error_message: str,
) -> None:
    """
    Generate a DICOM Encapsulated PDF *error* result for a failed job.

    Same DICOM structure as ``generate_epdf_dcm()`` but the encapsulated
    PDF contains a plain-text error description instead of real analysis
    results.

    Best-effort:
      - Tries to read input DICOMs to preserve patient/study tags + credential block.
      - If the input directory is empty or unreadable, emits a minimal ePDF with
        no donor metadata — the credential block will be absent (meaning the
        outbound AppWay Link may not be able to route it back, but at least
        there is a persistent record in S3 and operators get the SNS alert).
    """
    now = datetime.now(timezone.utc)
    date_str = now.strftime("%Y%m%d")
    time_str = now.strftime("%H%M%S")

    # ── Best-effort read of input DICOMs for donor metadata ──
    donor_ds: Optional[Dataset] = None
    input_infos: list[dict] = []
    try:
        dcm_files = sorted(input_dir.rglob("*.dcm")) if input_dir.exists() else []
        if dcm_files:
            input_infos, donor_ds = _collect_input_info(dcm_files)
    except Exception:
        logger.exception("[%s] Could not read input DICOMs while building error ePDF", job_id)

    # ── Build error PDF ──
    pdf_bytes = _build_error_pdf_bytes(job_id, error_message, now)
    logger.info("[%s] Generated ERROR PDF: %d bytes", job_id, len(pdf_bytes))

    # ── Build DICOM dataset ──
    # DocumentTitle and SeriesDescription are VR LO (max 64 chars).
    short_err_title = f"{SOLUTION_NAME} ERROR {job_id}"[:64]
    ds = _base_dicom_dataset(donor_ds, date_str, time_str)
    ds.SeriesDescription = short_err_title
    ds.ImageComments = f"ERROR result from {SOLUTION_NAME}: {(error_message or '')[:200]}"
    ds.DocumentTitle = short_err_title
    ds.MIMETypeOfEncapsulatedDocument = "application/pdf"
    ds.EncapsulatedDocument = pdf_bytes
    ds.ConceptNameCodeSequence = Sequence([])

    _attach_referenced_inputs(ds, input_infos)

    # ── Copy credential block ──
    if donor_ds is not None:
        _copy_credential_block(ds, donor_ds, job_id)
    else:
        logger.warning(
            "[%s] No donor DICOM available — error ePDF will NOT have credential block. "
            "AppWay Link may not route it back.", job_id,
        )

    # ── Save ──
    output_path.parent.mkdir(parents=True, exist_ok=True)
    ds.save_as(str(output_path), implicit_vr=False, little_endian=True)
    logger.info(
        "[%s] ERROR ePDF DICOM saved → %s  (%d bytes)",
        job_id, output_path, output_path.stat().st_size,
    )
